services:
  agro-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: agro-tracker-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=TwojeSilneHaslo123!
    volumes:
      - agro_data:/var/opt/mssql

volumes:
  agro_data:
